# Generated by Django 5.0.6 on 2024-07-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
