# Generated by Django 5.0.7 on 2024-07-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_students_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['Name'], 'verbose_name_plural': 'Students'},
        ),
    ]
